### ISSUE TITLE
Some issues in MainActivity and SurveysOverviewFragment implementation

### ISSUE THREAD

**Issue by luongvo** [ngocmanh1609/hotel-survey-android#10]
- Too many callbacks I think: `MainActCallback`, `SurveysBoundaryCallback`. I don't say it was wrong but it looks ugly for someone else takes a look to your code and try to understand it.
- Can we remove usage of `MainActivityFactory`? We have another way to init callback between activity and fragment, such as `onAttach` in fragment. https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/main/MainActivityFactory.kt#L9
- Why do we need to pass `viewmodel` to `fragment_surveys_overview` binding, even for `activity_main` or `fragment_surveys_detail`? https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/surveys_overview/SurveysOverviewFragment.kt#L34
- What does `loadImageThumbnailRequest` mean? So the idea is while loading the main large image, we have to load another smaller image for thumbnail??? What happens before the thumbnail be loaded? https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/surveys_overview/SurveysViewHolder.kt#L29
- `SurveysViewHolder` could be in `SurveysOverviewAdapter` I think

**Comment by ngocmanh1609** [comment]
> Can we remove usage of MainActivityFactory? We have another way to init callback between activity and fragment, such as onAttach in fragment.

Yes, I think I change to other way to do it without callback. Thanks.

> Why do we need to pass viewmodel to fragment_surveys_overview binding, even for activity_main or fragment_surveys_detail?

Will remove it, thanks.

> What does loadImageThumbnailRequest mean? So the idea is while loading the main large image, we have to load another smaller image for thumbnail??? What happens before the thumbnail be loaded?

My idea is described exactly by you. I think I will find a placeholder image before image is loaded. Thanks.

> SurveysViewHolder could be in SurveysOverviewAdapter I think

Yes, I will move it. Thank you.

**Comment by ngocmanh1609** [comment]
Yup, I fixed all issues in PR #15 , please take a look at it, thank you.
