### ISSUE TITLE
Some issues in data layer

### ISSUE THREAD

**Issue by luongvo** [ngocmanh1609/hotel-survey-android#11]
- I'm feeling confused with the meaning of `isFirstTimeStartApp`, so if it's not the first time of the app run, we will try to do sth actually for first time action? 🤔 https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/main/MainActivityViewModel.kt#L36
- Also, `setIsFirstTimeStartApp` always set **false**, that means it does not make any sense here https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/data/local/SharedPrefHelper.kt#L27
- Why do we need to separate **dev** and **prod** room database by `LocalModule`? I think we should separate dev and prod app and db package also 🤔 https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/di/module/LocalModule.kt#L19
- Naming issues: 
  - `AccessTokenRequest` but `AuthorizationResponse`
  - `SurveysResult` is DTO should not be in `model` package

**Comment by ngocmanh1609** [comment]
> I'm feeling confused with the meaning of isFirstTimeStartApp, so if it's not the first time of the app run, we will try to do sth actually for first time action? 

I just add the username and password into app for the first time after installing app. Please don't worry about that, thank you :smile_cat: 

> Also, setIsFirstTimeStartApp always set false, that means it does not make any sense here

Hix, It is a bug. I will fix it, thankssssssssss

> Why do we need to separate dev and prod room database by LocalModule? I think we should separate dev and prod app and db package also
Oh okay, I set it for the purpose that one app can be built in many environments i.e prod, staging, dev. I will remove that, thanks.

> Naming issues:
AccessTokenRequest but AuthorizationResponse
SurveysResult is DTO should not be in model package

I will fix it, thanks.

**Comment by ngocmanh1609** [comment]
These bugs is fixed in PR #15 , please take a look at it or switch to `develop` branch to see the newest code, thanks.

**Comment by luongvo** [comment]
What I meant in the first review is, I saw the confusion idea of the name of the method and its usage. Please look carefully at the condition `if (!prefHelper.isFirstTimeStartApp()) {`, 🤔 
https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/main/MainActivityViewModel.kt#L36

At least the method name should be `isNotFirstTimeStartApp` 🤷‍♂

**Comment by ngocmanh1609** [comment]
Ahhhhhhhhhhhh okay, I understood the problem here. So confusing!! Bug is here with wrong naming -> wrong condition. It should be `if (prefHelper.isFirstTimeStartApp()` and the default value should be `true` instead of `false` :joy_cat: Thanks, bro

**Comment by ngocmanh1609** [comment]
I fixed this issue in PR #16 , please take a look at it, thank you!
