### ISSUE TITLE
Can we have a better implementation for `InternetConnectionListener`?

### ISSUE THREAD

**Issue by luongvo** [ngocmanh1609/hotel-survey-android#12]
- It is not nice to keep anything related to the app at the Application class, it's such a bad practice. Since you already had Dagger which could provide appContext in its graph, for such thing like InternetConnectionListener, I think it should be mapped out to a separated component; use when you need it by just inject. https://github.com/ngocmanh1609/hotel-survey-android/search?utf8=%E2%9C%93&q=InternetConnectionListener&type=
- Why do we need to put `NetworkState` enum in `Constant` object? https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/common/Constant.kt#L4

**Comment by ngocmanh1609** [comment]
> It is not nice to keep anything related to the app at the Application class, it's such a bad practice. Since you already had Dagger which could provide appContext in its graph, for such thing like InternetConnectionListener, I think it should be mapped out to a separated component; use when you need it by just inject.

I'll change the flow to implementation for `InternetConnectionListener` and remove it out of Application class. Thank you!

> Why do we need to put NetworkState enum in Constant object?

I think I can store global object into Constant object. How about your way? Thanks.

**Comment by luongvo** [comment]
> I think I can store global object into Constant object. How about your way? Thanks.

Why don't we keep `NetworkState` enum as a separated enum class in a separated file, and put it a suitable package 🤷‍♂

**Comment by ngocmanh1609** [comment]
> Why don't we keep `NetworkState` enum as a separated enum class in a separated file, and put it a suitable package

Yes, it's is a good alternative way. :+1:

**Comment by ngocmanh1609** [comment]
I moved the connection listener out of App, and made some changes, please take a look in PR #14 , thank you.

**Comment by luongvo** [comment]
I think now we could move `isInternetAvailable()` in App class into a util method instead

**Comment by ngocmanh1609** [comment]
Okay, I will edit and remove some redundant files that no longer needed, please wait. Thanks :+1:

**Comment by ngocmanh1609** [comment]
hi @luongvo , I created PR #16 that fixed all issues above, please take a look, thank you.
