### ISSUE TITLE
Too convoluted connections in each layers

### ISSUE THREAD

**Issue by luongvo** [ngocmanh1609/hotel-survey-android#13]
Too convoluted connections in each layer, say for example: 
- What are the purpose of `HotelSurveyRepository` vs `SurveysBoundaryCallback`? Why does `HotelSurveyRepository` in network layer constraints to  `SurveysBoundaryCallback`? That's a not a good implementation at all. https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/data/repository/HotelSurveyRepository.kt#L20
-

**Comment by ngocmanh1609** [comment]
Oh, I will reorganize the workflow here and find if there is something else. Thanks

**Comment by ngocmanh1609** [comment]
Yes, I solved the convoluted connections in some place, please take a look in PR #15 , thank you.
