### ISSUE TITLE
Some issues in network layer

### ISSUE THREAD

**Issue by luongvo** [ngocmanh1609/hotel-survey-android#8]
Hi @ngocmanh1609, I'm Lucas from Nimble. Nice to meet you again here 👋 
I'll take care of reviewing your assignment and give you some feedback here from our side by opening issue tickets. Please feel free to catch up on this and help us know more about you by discussing and resolving the issues. In case you want to make changes to resolve the issues, please open a separated PR for each, then merge it if you think you did well and continue to others, we will take a look at it later 🆗 

Firstly, you're doing well, the build is running smoothly and has a good ui 👌
But, when checking your code, there is something makes me confused and could be improved in the network layer:
- "Authorization" is a header and it should be configurated automatically via retrofit interceptor instead of in each api call definitions https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/data/remote/Api.kt#L13
- Why do we need to keep `ApiService` instance within `ApiServiceHolder`? I think we should separate retrofit instances between the main api (with access token) vs auth api (no token required), that means we don't need `ApiServiceHolder` https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/di/interceptor/AuthorizationInterceptor.kt#L26
- NetworkModule: why do some config in object? https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/di/module/NetworkModule.kt#L67

**Comment by ngocmanh1609** [comment]
Hi @luongvo , nice to meet you again, and so many issues need to be resolved. :+1: 
I will explain about the confusing problems and refactor the source code based on your solution. For the issue with PR, I'll add it into comment after completed then you can track it easily.

> "Authorization" is a header and it should be configurated automatically via retrofit interceptor instead of in each api call definitions

Okay, I will add the header into Interceptor.

> Why do we need to keep ApiService instance within ApiServiceHolder? I think we should separate retrofit instances between the main api (with access token) vs auth api (no token required), that means we don't need ApiServiceHolder

I have the problem when using AuthorizationInterceptor that this interceptor requires ApiService instance, the api service depends on OKHttpClient, but OKHttpClient depends on AuthorizationInterceptor again. It causes `dependency cycle` error, so I need a place to store ApiService to avoid error. This is my current solution to call getToken Api in case it is expired. I will try to separate retrofit instance for this issue, thank you.

> NetworkModule: why do some config in object?

Oh, I just use to test in some cases, I will remove it, thanks.

**Comment by ngocmanh1609** [comment]
Hi @luongvo , I fixed these issues in PR #14 , and the newest code in `develop` branch now. Please take a look at it, thank you :smiley_cat:

**Comment by luongvo** [comment]
Would love to see you're active on feedback resolving, appreciate that 👍

**Comment by ngocmanh1609** [comment]
Yeah, the best approach is taking the feedback to improve myself :tada: You have very good solutions for my problems, thank you :100:
