### ISSUE TITLE
Some issues in SurveysDetailFragment implementation

### ISSUE THREAD

**Issue by luongvo** [ngocmanh1609/hotel-survey-android#9]
- Does `SurveysDetailViewModel` need `HotelSurveyRepository`?  https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/surveys_detail/SurveysDetailViewModel.kt#L11
- Why do we pass data via callback instead of fragment args? https://github.com/ngocmanh1609/hotel-survey-android/blob/2a2d6beea95b917ba392ef50b9cf4780bd1a47e2/app/src/main/java/com/example/android/hotelsurvey/ui/surveys_detail/SurveysDetailFragment.kt#L39

**Comment by ngocmanh1609** [comment]
> Does SurveysDetailViewModel need HotelSurveyRepository?

Sorry, I will change it.

> Why do we pass data via callback instead of fragment args?

Currently I call api to get data from database in Activity, then I send the received data to fragment. I will change the way to call api and remove the callback too. Thanks

**Comment by ngocmanh1609** [comment]
I did some change, and removed callbacks along with Factory class, please take a look at PR #15 , thank you.
